"""Type stubs for the PyO3-compiled ``_engine`` extension.

Kept in sync by hand with ``src/lib.rs``. Each phase 1 step that adds
Rust-exported methods updates this file in the same commit.
"""

from collections.abc import Callable
from typing import Any

class QuickJSError(Exception): ...
class JSError(QuickJSError): ...
class MarshalError(QuickJSError): ...
class InvalidHandleError(QuickJSError): ...

class Undefined:
    def __new__(cls) -> Undefined: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

UNDEFINED: Undefined

class QjsRuntime:
    def __new__(
        cls,
        *,
        memory_limit: int | None = ...,
        stack_limit: int | None = ...,
    ) -> QjsRuntime: ...
    def set_interrupt_handler(self, handler: Callable[[], Any]) -> None: ...
    def clear_interrupt_handler(self) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...

class QjsContext:
    def __new__(cls, runtime: QjsRuntime) -> QjsContext: ...
    def eval(
        self,
        code: str,
        *,
        module: bool = False,
        strict: bool = False,
        filename: str = "<eval>",
    ) -> Any: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def global_object(self) -> QjsHandle: ...
    def eval_handle(
        self,
        code: str,
        *,
        module: bool = False,
        strict: bool = False,
        filename: str = "<eval>",
    ) -> QjsHandle: ...
    def set_host_call_dispatcher(
        self, dispatcher: Callable[[int, tuple[Any, ...]], Any]
    ) -> None: ...
    def register_host_function(
        self, name: str, fn_id: int, is_async: bool = False
    ) -> None: ...

class QjsHandle:
    @property
    def context_id(self) -> int: ...
    @property
    def type_of(self) -> str: ...
    def is_promise(self) -> bool: ...
    def get(self, key: str) -> QjsHandle: ...
    def get_index(self, index: int) -> QjsHandle: ...
    def set(self, key: str, value: Any) -> None: ...
    def has(self, key: str) -> bool: ...
    def call(self, *args: Any) -> QjsHandle: ...
    def call_method(self, name: str, *args: Any) -> QjsHandle: ...
    def new_instance(self, *args: Any) -> QjsHandle: ...
    def to_python(self, *, allow_opaque: bool = False) -> Any: ...
    def dup(self) -> QjsHandle: ...
    def dispose(self) -> None: ...
    def is_disposed(self) -> bool: ...
