"""Type stubs for the PyO3-compiled ``_engine`` extension.

Kept in sync by hand with ``src/lib.rs``. Each phase 1 step that adds
Rust-exported methods updates this file in the same commit.
"""

from collections.abc import Callable
from typing import Any

class QuickJSError(Exception): ...
class JSError(QuickJSError): ...
class MarshalError(QuickJSError): ...
class InvalidHandleError(QuickJSError): ...

class Undefined:
    def __new__(cls) -> Undefined: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

UNDEFINED: Undefined

class QjsRuntime:
    def __new__(
        cls,
        *,
        memory_limit: int | None = ...,
        stack_limit: int | None = ...,
    ) -> QjsRuntime: ...
    def set_interrupt_handler(self, handler: Callable[[], Any]) -> None: ...
    def clear_interrupt_handler(self) -> None: ...
    def run_gc(self) -> None: ...
    def memory_usage(self) -> dict[str, int]: ...
    def add_module_source(
        self, scope_path: str, key: str, canonical_path: str, source: str
    ) -> None: ...
    def register_subscope(self, scope_path: str, child_key: str) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...

class QjsContext:
    def __new__(cls, runtime: QjsRuntime) -> QjsContext: ...
    def eval(
        self,
        code: str,
        *,
        module: bool = False,
        strict: bool = False,
        filename: str = "<eval>",
    ) -> Any: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def global_object(self) -> QjsHandle: ...
    def eval_handle(
        self,
        code: str,
        *,
        module: bool = False,
        strict: bool = False,
        promise: bool = False,
        filename: str = "<eval>",
    ) -> QjsHandle: ...
    def eval_module_async(
        self,
        code: str,
        *,
        filename: str = "<eval>",
    ) -> QjsHandle: ...
    def set_host_call_dispatcher(
        self, dispatcher: Callable[[int, tuple[Any, ...]], Any]
    ) -> None: ...
    def set_async_host_dispatcher(
        self, dispatcher: Callable[[int, tuple[Any, ...], int], int]
    ) -> None: ...
    def register_host_function(
        self, name: str, fn_id: int, is_async: bool = False
    ) -> None: ...
    def resolve_pending(self, pending_id: int, value: Any) -> None: ...
    def reject_pending(
        self, pending_id: int, name: str, message: str, stack: str | None = None
    ) -> None: ...
    def promise_state(self, handle: QjsHandle) -> int: ...
    def promise_result(self, handle: QjsHandle) -> QjsHandle: ...
    def run_pending_jobs(self) -> int: ...
    def set_in_sync_eval(self, value: bool) -> None: ...
    def take_sync_eval_hit_async_call(self) -> bool: ...

class QjsHandle:
    @property
    def context_id(self) -> int: ...
    @property
    def type_of(self) -> str: ...
    def is_promise(self) -> bool: ...
    def get(self, key: str) -> QjsHandle: ...
    def get_index(self, index: int) -> QjsHandle: ...
    def set(self, key: str, value: Any) -> None: ...
    def has(self, key: str) -> bool: ...
    def call(self, *args: Any) -> QjsHandle: ...
    def call_method(self, name: str, *args: Any) -> QjsHandle: ...
    def new_instance(self, *args: Any) -> QjsHandle: ...
    def to_python(self, *, allow_opaque: bool = False) -> Any: ...
    def dup(self) -> QjsHandle: ...
    def dispose(self) -> None: ...
    def is_disposed(self) -> bool: ...
